# KNN

In [4]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as metrics
import model_evaluator
import data_import

In [5]:
# Import data
X_tot, df_tot, X_train, X_test, y_train, y_test = data_import.import_data_train_test()

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
y_test_predicted = knn_clf.predict(X_test).reshape(-1,1)
print('Accuracy on testing: %f%%' % (model_evaluator.compute_accuracy(y_test, y_test_predicted)*100))
y_train_predicted = knn_clf.predict(X_train).reshape(-1,1)
print('Accuracy on training: %f%%' % (model_evaluator.compute_accuracy(y_train, y_train_predicted)*100))

/home/ippo/anaconda3/envs/malis/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy on testing: 99.529936%
Accuracy on training: 99.690728%


In [10]:
kfold_scores_accuracy = model_evaluator.kfold_cross_validation(knn_clf, X_train, y_train, k=5, scoring='accuracy')
kfold_scores_accuracy

array([0.99536178, 0.99443414, 0.9938138 , 0.9938138 , 0.99257655])

In [9]:
kfold_scores_npv = model_evaluator.kfold_cross_validation(knn_clf, X_train, y_train, k=5, scoring='precision')
kfold_scores_npv

array([0.99253225, 0.99189737, 0.98710115, 0.98789509, 0.98675035])

In [16]:
for i in range(1,10):
    knn_clf = KNeighborsClassifier(n_neighbors=i)
    kfold_scores_npv = model_evaluator.kfold_cross_validation(knn_clf, X_train, y_train, k=5, scoring='precision')
    print("i= " + str(i))
    print(kfold_scores_npv);

i= 1
[0.99727149 0.99390657 0.98977505 0.98989899 0.9922807 ]
i= 2
[0.99253731 0.99123399 0.98643148 0.98791135 0.98675958]
i= 3
[0.99253225 0.99189737 0.98710115 0.98789509 0.98675035]
i= 4
[0.99254743 0.98725687 0.98577236 0.98592493 0.98607242]
i= 5
[0.99252717 0.98725687 0.98641304 0.98724832 0.98743017]
i= 6
[0.98784605 0.98725687 0.98440678 0.98460509 0.98467967]
i= 7
[0.98784605 0.98724832 0.98574338 0.98525469 0.98467967]
i= 8
[0.98322148 0.98460509 0.98507463 0.98327759 0.98263889]
i= 9
[0.98384926 0.98657718 0.98507463 0.98393574 0.98332175]
